### ISSUE TITLE
Something wrong with  mouth_aspect_ratio( ) function.

### ISSUE THREAD

**Issue by dyyzhmm** [mauckc/mouth-open#1]
As you written:
        (mStart, mEnd) = (49, 68)
        mouth = shape[mStart:mEnd]
        A = dist.euclidean(mouth[2], mouth[9]) # 51, 59
	B = dist.euclidean(mouth[4], mouth[7]) # 53, 57
	C = dist.euclidean(mouth[0], mouth[6]) # 49, 55

If，mouth[0] means point 49, mouth[6] means point 55, then mouth 9 should be point 58 but not 59, mouth 7 should be 56 but not 57.

**Comment by mauckc** [comment]
Thank you, I will take a look at the mouth landmark array.

**Comment by mauckc** [comment]
For reference, here is are the labeled face landmarks:

![face_landmarks](https://user-images.githubusercontent.com/8161032/59376889-e4884700-8d05-11e9-98ba-be441e576298.png)

**Comment by mauckc** [comment]
updated the mouth landmark array in webcam file, will update video script later
